### ISSUE TITLE
Vertical Knob support

### ISSUE THREAD

**Issue by neomib** [dmitrymorozoff/react-circular-slider#13]
Hi
Thanks for the library. I am asked to display an audio knob which (according to our Audio guys) suppose to let users change the value by moving the mouse vertically. 

What they want is when a user moves the mouse vertically he will be able to change the value from 0 100% and vice versa. Today I see it allows to change the value only half way when moving vertically.

Is there a way to add this functionality? I don't mind making a pull request just point me in the right direction...

Thanks!

**Comment by neomib** [comment]
??

**Comment by dmitrymorozoff** [comment]
@neomib Hey. Sorry for the wait. Can you describe in more detail what you need. Or attach a screenshot

**Comment by neomib** [comment]
![vertical knob](https://user-images.githubusercontent.com/14325903/55679993-d7716500-591c-11e9-8196-61ef952f50bd.gif)

**Comment by neomib** [comment]
Sometimes it goes all the way till 100% but not as smoothly as I expect it..thanks

**Comment by dmitrymorozoff** [comment]
no, this feature is not implemented for now
